# -*- coding: utf-8 -*-
"""Fine_tuning_Lab_task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fiyi540M-yPlbQUXQzh5t58O_ocec-Ko

# Fine-Tuning a Small Language Model on SQuAD Dataset

## Task Overview
This notebook demonstrates fine-tuning a small language model (DistilBERT with ~66M parameters) on the SQuAD dataset for Question Answering task.

### Steps:
1. Install required libraries
2. Load and explore the dataset
3. Preprocess data (tokenization)
4. Load a pre-trained SLM
5. Fine-tune the model
6. Evaluate using EM and F1 metrics

## Step 1: Install Required Libraries

pip install transformers datasets accelerate evaluate

## Load Dataset
"""

from datasets import load_dataset

# Load a dataset from Hugging Face
dataset = load_dataset('squad')

# Create smaller train/validation subsets to reduce training time
train_subset_size = 20000  # you can adjust if needed
val_subset_size = 5000

train_dataset_small = dataset["train"].shuffle(seed=42).select(range(train_subset_size))
validation_dataset_small = dataset["validation"].shuffle(seed=42).select(range(val_subset_size))

# Print the dataset structure and subset sizes
print(dataset)
print(f"Using train subset of size: {len(train_dataset_small)}")
print(f"Using validation subset of size: {len(validation_dataset_small)}")

"""Let's inspect a sample from the training split to see the data format."""

# Display a sample from the training split
print(dataset['train'][0])

from transformers import AutoTokenizer, AutoModelForQuestionAnswering

# Model selection: DistilBERT has ~66M parameters (much less than 3B)
model_name = "distilbert-base-uncased"

# Load the tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_name)

# Load the model
model = AutoModelForQuestionAnswering.from_pretrained(model_name)

print(f"Loaded model: {model_name}")
print(f"Model parameters: {model.num_parameters() / 1e6:.2f} Million")

"""## Step 3: Preprocess Data for Fine-tuning

### Important Note:
Tokenizer and model must be loaded BEFORE preprocessing. We now have both ready to use in the data preparation step.

For the SQuAD dataset, we tokenize questions and contexts. Since answers are spans within the context, we handle answer mapping during tokenization.
"""

max_length = 384  # The maximum length of a feature (question and context)
stride = 128  # The overlap between consecutive chunks of a context

def preprocess_training_examples(examples):
    questions = [q.strip() for q in examples["question"]]
    inputs = tokenizer(
        questions,
        examples["context"],
        max_length=max_length,
        truncation="only_second", # Truncate only the context if it's too long
        stride=stride,
        return_overflowing_tokens=True,
        return_offsets_mapping=True,
        padding="max_length",
    )

    offset_mapping = inputs.pop("offset_mapping")
    sample_map = inputs.pop("overflow_to_sample_mapping")
    answers = examples["answers"]
    start_positions = []
    end_positions = []

    for i, offset in enumerate(offset_mapping):
        sample_idx = sample_map[i]
        answer = answers[sample_idx]
        start_char = answer["answer_start"][0]
        end_char = start_char + len(answer["text"][0])

        sequence_ids = inputs.sequence_ids(i)

        # Find the start and end of the context
        idx = 0
        while sequence_ids[idx] != 1: # Find where the context starts
            idx += 1
        context_start = idx
        while sequence_ids[idx] == 1: # Find where the context ends
            idx += 1
        context_end = idx - 1

        # If the answer is not fully contained in the current context chunk, set it to (0, 0)
        if offset[context_start][0] > start_char or offset[context_end][1] < end_char:
            start_positions.append(0)
            end_positions.append(0)
        else:
            # Otherwise it's the start and end token positions
            idx = context_start
            while idx <= context_end and offset[idx][0] <= start_char:
                idx += 1
            start_positions.append(idx - 1)

            idx = context_end
            while idx >= context_start and offset[idx][1] >= end_char:
                idx -= 1
            end_positions.append(idx + 1)

    inputs["start_positions"] = start_positions
    inputs["end_positions"] = end_positions
    return inputs

# Apply the preprocessing to the (smaller) training subset
tokenized_train_dataset = train_dataset_small.map(
    preprocess_training_examples,
    batched=True,
    remove_columns=train_dataset_small.column_names,
)

print("Original full training dataset size:", len(dataset["train"]))
print("Training subset size:", len(train_dataset_small))
print("Tokenized training dataset size (subset):", len(tokenized_train_dataset))
print("Sample tokenized training example:", tokenized_train_dataset[0])

def preprocess_validation_examples(examples):
    questions = [q.strip() for q in examples["question"]]
    inputs = tokenizer(
        questions,
        examples["context"],
        max_length=max_length,
        truncation="only_second",
        stride=stride,
        return_overflowing_tokens=True,
        return_offsets_mapping=True,
        padding="max_length",
    )

    sample_map = inputs.pop("overflow_to_sample_mapping")
    inputs["example_id"] = [examples["id"][idx] for idx in sample_map]
    # Keep offset_mapping for post-processing (no redundant assignment)
    offset_mapping = inputs.pop("offset_mapping")
    inputs["offset_mapping"] = offset_mapping

    # Add sequence_ids to the features for post-processing
    inputs["sequence_ids"] = [inputs.sequence_ids(i) for i in range(len(inputs["input_ids"]))]

    return inputs

# Apply the preprocessing to the (smaller) validation subset
tokenized_validation_dataset = validation_dataset_small.map(
    preprocess_validation_examples,
    batched=True,
    remove_columns=validation_dataset_small.column_names,
)

print("Original full validation dataset size:", len(dataset["validation"]))
print("Validation subset size:", len(validation_dataset_small))
print("Tokenized validation dataset size (subset):", len(tokenized_validation_dataset))

"""## Fine-tune Model

### Subtask:
Fine-tune the selected SLM on the preprocessed text dataset. This will involve setting up training arguments and using the `Trainer` API from the `transformers` library.

We'll define a `DataCollatorForQuestionAnswering` to prepare batches and use `TrainingArguments` to configure our training process.
"""

from transformers import TrainingArguments, Trainer, DataCollatorWithPadding

# Define a data collator. This will pad your batches to the longest example in each batch.
data_collator = DataCollatorWithPadding(tokenizer)

# Define training arguments
training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch", # Corrected argument name
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    weight_decay=0.01,
    fp16=True, # Enable mixed precision training for faster training if GPU is available
    push_to_hub=False, # Set to True if you want to push your model to Hugging Face Hub
)

# Initialize the Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train_dataset,
    eval_dataset=tokenized_validation_dataset,
    data_collator=data_collator,
)

# Start training
trainer.train()

"""## Evaluate Model Performance

### Subtask:
Evaluate the fine-tuned model using suitable metrics.

For Question Answering on SQuAD, we will calculate Exact Match (EM) and F1 Score. This requires generating predictions, post-processing them to extract answers, and then comparing with the ground truth using the SQuAD evaluation script from the `evaluate` library.
"""

import collections
import numpy as np
from tqdm.auto import tqdm

print("Generating predictions on the (smaller) validation subset...")
raw_predictions = trainer.predict(tokenized_validation_dataset)

def postprocess_qa_predictions(examples, features, raw_predictions, n_best_size=20, max_answer_length=30):
    all_start_logits, all_end_logits = raw_predictions

    example_id_to_index = {k: i for i, k in enumerate(examples["id"])}
    features_per_example = collections.defaultdict(list)
    for i, feature in enumerate(features):
        features_per_example[example_id_to_index[feature["example_id"]]].append(i)

    # The dictionary to fill with the processed predictions
    predictions = collections.OrderedDict()

    # tqdm displays progress bar.
    print("Post-processing predictions...")
    for example_index, example in enumerate(tqdm(examples)):
        feature_indices = features_per_example[example_index]
        min_null_score = None
        valid_answers = []

        context = example["context"]
        for feature_index in feature_indices:
            start_logits = all_start_logits[feature_index]
            end_logits = all_end_logits[feature_index]
            offset_mapping = features[feature_index]["offset_mapping"]

            cls_index = features[feature_index]["input_ids"].index(tokenizer.cls_token_id)
            feature_null_score = start_logits[cls_index] + end_logits[cls_index]
            if min_null_score is None or min_null_score < feature_null_score:
                min_null_score = feature_null_score

            start_indexes = np.argsort(start_logits)[-1 : -n_best_size - 1 : -1].tolist()
            end_indexes = np.argsort(end_logits)[-1 : -n_best_size - 1 : -1].tolist()
            for start_index in start_indexes:
                for end_index in end_indexes:
                    if (start_index >= len(offset_mapping) or
                        end_index >= len(offset_mapping) or
                        offset_mapping[start_index] is None or
                        offset_mapping[end_index] is None or
                        offset_mapping[start_index][0] < 0 or
                        offset_mapping[end_index][0] < 0 or
                        start_index > end_index or
                        (features[feature_index]["sequence_ids"][start_index] != 1 or
                         features[feature_index]["sequence_ids"][end_index] != 1)):
                        continue

                    length = offset_mapping[end_index][1] - offset_mapping[start_index][0]
                    if length > max_answer_length:
                        continue

                    valid_answers.append(
                        {
                            "offsets": (offset_mapping[start_index][0], offset_mapping[end_index][1]),
                            "score": start_logits[start_index] + end_logits[end_index],
                            "start_logit": start_logits[start_index],
                            "end_logit": end_logits[end_index],
                        }
                    )

        if len(valid_answers) > 0:
            best_answer = sorted(valid_answers, key=lambda x: x["score"], reverse=True)[0]
        else:
            # In the event that all valid answers have been filtered out, return an empty string
            best_answer = {"offsets": (0, 0), "score": 0.0, "start_logit": 0.0, "end_logit": 0.0}

        # If the null answer has a better score than the best non-null answer, then return null answer.
        if min_null_score is not None and min_null_score > best_answer["score"]:
            predictions[example["id"]] = ""
        else:
            predictions[example["id"]] = context[best_answer["offsets"][0] : best_answer["offsets"][1]]

    return predictions

# Call the post-processing function on the validation subset
final_predictions = postprocess_qa_predictions(
    validation_dataset_small, tokenized_validation_dataset, raw_predictions.predictions
)

print("Finished generating and post-processing predictions on the validation subset.")

# Compute SQuAD metrics (Exact Match and F1) on the validation subset
# This cell only depends on `final_predictions` and `validation_dataset_small`.

!pip install evaluate  # safe to re-run; does nothing if already installed
import evaluate

print("Computing SQuAD metrics (Exact Match and F1) on validation subset...")

# Load the SQuAD evaluation script
squad_metric = evaluate.load("squad")

# Prepare the references in the format expected by the SQuAD metric
references = [
    {"id": ex["id"], "answers": ex["answers"]}
    for ex in validation_dataset_small
]

# Convert final_predictions (dict id -> text) to the list-of-dicts format expected by the metric
predictions_for_metric = [
    {"id": qid, "prediction_text": pred_text}
    for qid, pred_text in final_predictions.items()
]

# Compute the metrics
eval_results = squad_metric.compute(predictions=predictions_for_metric, references=references)

print("\n" + "="*60)
print("SQuAD Evaluation Results (on validation subset):")
print("="*60)
print(f"Exact Match (EM): {eval_results['exact_match']:.4f}")
print(f"F1 Score: {eval_results['f1']:.4f}")
print("="*60)

"""## Summary and Observations

### Task Completion:
✓ **Dataset Selected**: SQuAD - Different from standard classification tasks  
✓ **Model Selected**: DistilBERT (~66M parameters) - Much less than 3B limit  
✓ **Task Completed**: Question Answering fine-tuning  
✓ **Evaluation Metrics**: Exact Match (EM) and F1 Score (standard for QA)  
✓ **Results Displayed**: Clear performance metrics shown  

### Key Implementation Details:
1. **DistilBERT Model**: Compact version of BERT (66M vs 110M parameters)
2. **Data Preprocessing**: Tokenization with sliding window approach for long contexts
3. **Training Configuration**: 3 epochs with learning rate 2e-5
4. **Evaluation**: SQuAD metrics using HuggingFace evaluate library
5. **GPU Acceleration**: Mixed precision training (fp16) enabled for faster training

### Results Interpretation:
- **Exact Match**: Percentage of predictions matching ground truth exactly
- **F1 Score**: Harmonic mean of precision and recall at token level
- Higher values indicate better model performance on QA task
"""